const en = {
    fast_login:"Fast login",
    manage:"Manage",
    cancel:"Cancel",
    confirm:"Confirm",
    continue:"Continue",
    creat_sub_acc:"Create sub-account",
    trade_acc:"Trade account",
    set_pwd:"Set password",
    old_pwd:"Old password",
    new_pwd:"Set password",
    pwd_length:"Please use any combination of 6-12 letters and numbers",
    con_pwd:"Confirm password",
    save:"Save",
    pwd_login:"Password login",
    send_code:"Send code",
    phone_no:"Phone number",
    enter_pwd:"Password",
    enter_vcode:"Vertification code",
    login:"login",
    foget_pwd:"Foget your password?",
    top:"Top",
    all:"All",
    export:'Export',
    pos:'Pos',
    search:"search",
    trade:'Trade',
    mine:"Mine",
    buy:"BUY",
    sell:"SELL",
    buy2:"BUY",
    sell2:"SELL",
    edit:"edit",
    add:"add",
    forex:"forex",
    metals:"metals",
    energy:"energy",
    CFD:"CFD",
    trade_time:"Trade time",
    quote_Time:"Quote Time",
    spread:"spread",
    digits:"digits",
    minstoplevel:"minstoplevel",
    contractSize:"contractSize"	,
    min_lots:"min lots",
    max_lots:"max lots"	,
    lot_step:"lot step"	,
    commission:"commission"	,
    storage_mode :"storage mode",
    deposit:"Deposit",	
    withdraw:"Withdraw",
    bank_cards:"Bank cards",
    wallet:"Wallet",
    product:"Product",
    new_price:"New price",
    confirm_trade:"confirm",
    confirm_hang:"confirm",
    fast_trade:"Fast trade",
    advanced:"Advanced",
    market:"Market",
    pending:"Pending",
    switch:"Switch",
    position:"Positon",
    history:"History",
    commission:"Commission",
    lots:"Lots",
    lot:"lot",
    not_set:"Not set",
    slp:"Stop loss",
    tpp:"Take profit",
    deadline:"Deadline",
    trade_action:"Action",
    pending_action:"Action",
    address:"Address"

}
const zh = {
    fast_login:"快捷登录",
    creat_sub_acc:"添加账户",
    trade_acc:"交易账户",
    manage:"账号管理",
    cancel:"取消",
    lots:"交易手数",
    lot:"手",
    confirm:"确定",
    continue:"继续",
    save:"保存",
    old_pwd:"请输入原密码",
    new_pwd:"请输入新密码",
    con_pwd:"确认密码",
    pwd_length:"请输入6到12位密码",
    set_pwd:"修改密码",
    pwd_login:"密码登录",
    send_code:"发送验证码",
    phone_no:"请输入手机号",
    enter_pwd:"请输入密码",
    enter_vcode:"请输入验证码",
    foget_pwd:"忘记密码?",
    login:"登 录",
    top:"分类高手",
    all:"综合高手",
    export:'跟单',
    search:"搜索",
    pos:"交易",
    trade:"自选",
    mine:"我的",
    buy:"买入",
    sell:"卖出",
    buy2:"买",
    sell2:"卖",
    edit:"编辑",
    add:"添加",
    forex:"外汇",
    metals:"贵金属",
    energy:"能源",
    CFD:"差价合约",
    trade_time:"交易时间",
    quote_Time:"报价时间",
    spread:"点差",
    digits:"小数位",
    minstoplevel:"最低止损盈点",
    contractSize:"合约数"	,
    min_lots:"最小交易量",
    max_lots:"最大交易量"	,
    lot_step:"交易步长"	,
    commission:"标准手手续费"	,
    storage_mode :"库存费计算模式",
    deposit:"充值",	
    withdraw:"提现",
    bank_cards:"银行卡",
    wallet:"钱包",
    product:"交易品种",
    new_price:"最新价格",
    confirm_hang:"确认挂单",
    confirm_trade:"确认交易",
    fast_trade:"简单",
    advanced:"高级",
    market:"市价交易",
    pending:"挂单交易",
    switch:"切换",
    position:"持仓",
    history:"历史",
    commission:"佣金",
    not_set:"未设置",
    slp:"止损价格",
    tpp:"止盈价格",
    deadline:"截止日期",
    trade_action:"交易类型",
    pending_action:"挂单类型",
    address:"请输入您的地址"
}

var McIntl = {
    language:1,//1:"zh",2:"en"

    message:function(message){
        if(this.language==1)
            return zh[message];
        else
            return en[message];

    }
}

module.exports = McIntl;
